name: Spine
options:
  bundleIdPrefix: com.heyitsmejosh
targets:
  Spine:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Spine]
    info:
      path: Spine/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.heyitsmejosh.spine
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QMM486NPYC
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
  SpineMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources: [Spine]
    info:
      path: Spine/Info.plist
      properties:
        UILaunchScreen: {}
        LSApplicationCategoryType: public.app-category.productivity
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.heyitsmejosh.spine
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QMM486NPYC
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
    entitlements:
      path: Spine/SpineMac.entitlements
      properties:
        com.apple.security.app-sandbox: true
